clients/urls.py
from django.urls import path, include
from clients.views import ClientListView, AddClient, UpdateClient, DeleteClient

urlpatterns = [
    path('', ClientListView.as_view(), name='clients'),
    path('add_client/', AddClient.as_view(), name='add_client'),
    path('update_client/<int:pk>/', UpdateClient.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', DeleteClient.as_view(), name='delete_client'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('website.urls', 'website'), namespace='website')),
    path('clients/', include(('clients.urls', 'clients'), namespace='clients')),
    path('jobs/', include(('jobs.urls', 'jobs'), namespace='jobs')),
    path('management/', include(('management.urls', 'management'), namespace='management')),

]

management/urls.py
from django.urls import path, include
from management.views import *

urlpatterns = [
    path('invoices/', InvoiceListView.as_view(), name='invoices'),
    path('invoices/add/', AddInvoice.as_view(), name='add_invoice'),
    path('invoices/update/<int:pk>/', UpdateInvoice.as_view(), name='update_invoice'),
    path('invoices/delete/<int:pk>/', DeleteInvoice.as_view(), name='delete_invoice'),
    path('invoices/view/<int:pk>/', ViewInvoice.as_view(), name='view_invoice'),
    path('invoices/pdf/', InvoiceListView.print_pdf, name='pdf_invoice'),
    path('invoices/report/', InvoiceListView.generate_excel_report, name='generate_report'),
    path('get_product_price/<int:product_id>/', get_product_price, name='get_product_price'),
    path('get_client_data/<int:client_id>/', get_client_datas, name='get_client_datas'),
    path('employees/', EmployeeListView.as_view(), name='employees'),
    path('employees/add/', AddEmployee.as_view(), name='add_employee'),
    path('employees/update/<int:pk>/', UpdateEmployee.as_view(), name='update_employee'),
    path('employees/delete/<int:pk>/', DeleteEmployee.as_view(), name='delete_employee'),
    path('products/', ProductListView.as_view(), name='products'),
    path('products/add/', AddProduct.as_view(), name='add_product'),
    path('products/update/<int:pk>/', UpdateProduct.as_view(), name='update_product'),
    path('products/delete/<int:pk>/', DeleteProduct.as_view(), name='delete_product'),
    path('category/', CategoryListView.as_view(), name='categories'),
    path('category/add/', AddCategory.as_view(), name='add_category'),
    path('category/update/<int:pk>/', UpdateCategory.as_view(), name='update_category'),
    path('category/delete/<int:pk>/', DeleteCategory.as_view(), name='delete_category'),
]

management/forms.py
from django import forms
from management.models import Employee, Invoice, Product, Category




class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'


class InvoiceForm(forms.ModelForm):

    class Meta:
        model = Invoice
        fields = '__all__'
        widgets = {
            'invoice_date': forms.DateInput(attrs={'type': 'date'}),
            'invoice_due_date': forms.DateInput(attrs={'type': 'date'}),
            
        }




class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'




management/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from management.models import Employee, Product, Invoice, Category
from clients.models import Client
from management.forms import EmployeeForm, ProductForm, InvoiceForm, CategoryForm
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.db.models import Q
from django.urls import reverse_lazy
import datetime
import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
from .pdf import html_to_pdf
from django.db.models.functions import ExtractYear
from openpyxl import Workbook
from openpyxl.styles import Alignment, PatternFill, Font, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.utils import column_index_from_string
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import JsonResponse

# Create your views here.


#EMPLOYEE VIEWS
class EmployeeListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Employee
    template_name = 'employees_list.html'
    context_object_name = 'employees'
    login_url = 'website:login'
    permission_required = 'management.view_employee'


    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query) |
                Q(last_name__icontains=search_query) |
                Q(category__icontains=search_query)
            )
        return queryset
    


class AddEmployee(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'add_employee.html'
    success_url = reverse_lazy('management:employees')
    login_url = 'website:login'
    permission_required = 'management.add_employee'

    def form_valid(self, form):
        form.instance.name = self.request.POST.get('name')
        return super().form_valid(form)


class UpdateEmployee(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'update_employee.html'
    success_url = reverse_lazy('management:employees')
    login_url = 'website:login'
    permission_required = 'management.change_employee'

    def form_valid(self, form):
        form.instance.employee = self.request.user.employee
        return super().form_valid(form)
    


class DeleteEmployee(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    model = Employee
    template_name = 'employee_confirm_delete.html'
    success_url = reverse_lazy('management:employees')
    login_url = 'website:login'
    permission_required = 'management.delete_employee'



#PRODUCT VIEWS

class ProductListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Product
    template_name = 'products_list.html'
    context_object_name = 'products'
    login_url = 'website:login'
    permission_required = 'management.view_product'

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search')
        if search_query:
            queryset = Product.objects.filter(
                Q(name__icontains=search_query) |
                Q(description__icontains=search_query) |
                Q(category__name__icontains=search_query)
            )
        return queryset
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        product_list = Product.objects.all()

        total_products = len(product_list)
        out_stock = []
        out_stock2 = []

        for product in product_list:
            if product.quantity <= 0:
                out_stock.append(product)
            elif product.quantity >= 1 and product.quantity < 10:
                out_stock2.append(product)

        total_out_stock = len(out_stock)
        total_out_stock2 = len(out_stock2)
        context['total_out_stock'] = total_out_stock
        context['total_out_stock2'] = total_out_stock2
        context['total_products'] = total_products

        return context
    

class AddProduct(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'add_product.html'
    success_url = reverse_lazy('management:products')
    login_url = 'website:login'
    permission_required = 'management.add_product'

    def form_valid(self, form):
        form.instance.name = self.request.POST.get('name')
        return super().form_valid(form)
    

class UpdateProduct(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'update_product.html'
    success_url = reverse_lazy('management:products')
    login_url = 'website:login'
    permission_required = 'management.change_product'

    def form_valid(self, form):
        form.instance.name = self.request.POST.get('name')
        return super().form_valid(form)


class DeleteProduct(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    model = Product
    template_name = 'product_confirm_delete.html'
    success_url = reverse_lazy('management:products')
    login_url = 'website:login'
    permission_required = 'management.delete_product'


#CATEGORY VIEWS


class CategoryListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Category
    template_name = 'categories_list.html'
    context_object_name = 'categories'
    login_url = 'website:login'
    permission_required = 'management.view_category'

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search')
        if search_query:
            queryset = Product.objects.filter(
                Q(name__icontains=search_query)
            )
        return queryset
    

class AddCategory(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'add_category.html'
    success_url = reverse_lazy('management:categories')
    login_url = 'website:login'
    permission_required = 'management.add_category'

    def form_valid(self, form):
        form.instance.name = self.request.POST.get('name')
        return super().form_valid(form)
    

class UpdateCategory(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'update_category.html'
    success_url = reverse_lazy('management:categories')
    login_url = 'website:login'
    permission_required = 'management.change_category'

    def form_valid(self, form):
        form.instance.name = self.request.POST.get('name')
        return super().form_valid(form)
    

class DeleteCategory(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    model = Category
    template_name = 'category_confirm_delete.html'
    success_url = reverse_lazy('management:categories')
    login_url = 'website:login'
    permission_required = 'management.delete_category'



#INVOICE VIEWS

class InvoiceListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Invoice
    template_name = 'invoices_list.html'
    context_object_name = 'invoices'
    login_url = 'website:login'
    permission_required = 'management.view_invoice'

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search')
        year = self.request.GET.get('year')
        if search_query:
            queryset = Invoice.objects.filter(
                Q(client__full_name__icontains=search_query) |
                Q(client_car__icontains=search_query) |
                Q(client_car_model__icontains=search_query) |
                Q(invoice_number__icontains=search_query)|
                Q(state__icontains=search_query)
            )

        if year:
            # Filtrar por el año seleccionado
            queryset = queryset.filter(invoice_date__year=year)

        return queryset
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        invoice_list = Invoice.objects.all()

        for invoice in invoice_list:
            if invoice.invoice_due_date <= datetime.date.today() and invoice.paid == False:
                invoice.state = "Expirada"
                invoice.save()
            elif invoice.invoice_due_date <= datetime.date.today() and invoice.paid == True:
                invoice.state = "Pagada"
                invoice.save()
            elif invoice.paid == True:
                invoice.state = "Pagada"
                invoice.save()
            elif invoice.paid == True and invoice.invoice_due_date > datetime.date.today():
                invoice.state = "Pagada"
                invoice.save()
            elif invoice.paid == False:
                invoice.state = "Pendiente"
                invoice.save()

        total_invoices = len(invoice_list)
        expired_invoices = len (invoice_list.filter(state="Expirada"))
        paid_invoices = len (invoice_list.filter(state="Pagada"))
        pending_invoices = len (invoice_list.filter(state="Pendiente"))



        context['total_invoices'] = total_invoices

management/templates/add_product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Agregar Stock
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 700px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        opacity: 70%;
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    .description-field {
        height: 100px;
    }

</style>

<div class="form-container">
    <img class="banner-image" src="{% static 'dist/img/addemployee.jpg' %}" alt="Imagen de banner">
    <br>
    <br>
    <h4 style="text-align: center; text-decoration: underline;">Agregar Stock</h4>
    <br>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="name_client">Nombre:</label>
            {{ form.name }}
        </div>
        <div>
            <label for="name_client">Categoria:</label>
            {{ form.category }}
        </div>
        <div>
            <label for="last_name">Precio:</label>
            {{ form.price }}
        </div>
        <div>
            <label for="email">Cantidad:</label>
            {{ form.quantity }}
        </div>
        <div>
            <label for="email">Descripcion:</label>
            {{ form.description }}
        </div>

        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}

management/templates/categories_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Categorias
{% endblock %}

{% block headerpage %}
Categorias
{% endblock %}

{% block content %}
<div class="container-fluid mt-5">
    <div class="table-header">
        <div class="search-container">
            <form method="GET" action="{% url 'management:categories' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="search" placeholder="Buscar...">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
        </div>
        <div class="add-button">
            <button>
                <a href={%url 'management:add_category' %} style="color:white">Agregar</a>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                </svg>
            </button>
        </div>
    </div>

    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th scope="col" style="text-align: center;">Nombre</th>
                    <th scope="col" style="text-align: center;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                <tr>
                    <td style="text-align: center;">{{ category.name }}</td>
                    <td style="text-align: center;">
                        <a href="{% url 'management:update_category' category.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'management:delete_category' category.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="9" style="text-align: center;">No se encontraron categorias.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination-container">
        <button id="prev-page-btn" class="btn btn-secondary btn-sm">Previous</button>
        <button id="next-page-btn" class="btn btn-secondary btn-sm">Next</button>
    </div>
</div>
{% endblock %}

management/templates/category_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Eliminar Categoria
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 600px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    form button[type="reset"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #f44336;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }


</style>

<div class="form-container">
    <form method="POST">
        {% csrf_token %}
        <p>¿Deseas eliminar la categoria {{ category.name }}?
        <br>
        <br>
        <button class="btn btn-success" type="submit">Si, eliminar</button>
        <button class="btn btn-danger" type="reset"><a href="{% url 'management:products' %}" style="color: white">No, Cancelar</a></button>
        </p>
    </form>
</div>
{% endblock %}

management/templates/employee_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Eliminar Empleado
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 600px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    form button[type="reset"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #f44336;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }


</style>

<div class="form-container">
    <form method="POST">
        {% csrf_token %}
        <p>¿Deseas eliminar el empleado {{ employee.name }}?
        <br>
        <br>
        <button class="btn btn-success" type="submit">Si, eliminar</button>
        <button class="btn btn-danger" type="reset"><a href="{% url 'clients:clients' %}" style="color: white">No, Cancelar</a></button>
        </p>
    </form>
</div>
{% endblock %}

management/templates/employees_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Empleados
{% endblock %}

{% block headerpage %}
Empleados
{% endblock %}

{% block content %}
<div class="container-fluid mt-5">
    <div class="table-header">
        <div class="search-container">
            <form method="GET" action="{% url 'management:invoices' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="search" placeholder="Buscar...">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
        </div>
        <div class="add-button">
            <button>
                <a href={%url 'management:add_employee' %} style="color:white">Agregar</a>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                </svg>
            </button>
        </div>
    </div>

    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th scope="col" style="text-align: center;">Nombre</th>
                    <th scope="col" style="text-align: center;">Apellidos</th>
                    <th scope="col" style="text-align: center;">Categoria</th>
                    <th scope="col" style="text-align: center;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td style="text-align: center;">{{ employee.name }}</td>
                    <td style="text-align: center;">{{ employee.last_name }}</td>
                    <td style="text-align: center;">{{ employee.category }}</td>
                    <td style="text-align: center;">
                        <a href="{% url 'management:update_employee' employee.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'management:delete_employee' employee.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="9" style="text-align: center;">No se encontraron empleados.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination-container">
        <button id="prev-page-btn" class="btn btn-secondary btn-sm">Previous</button>
        <button id="next-page-btn" class="btn btn-secondary btn-sm">Next</button>
    </div>
</div>
{% endblock %}

management/templates/product_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Eliminar Producto
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 600px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    form button[type="reset"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #f44336;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }


</style>

<div class="form-container">
    <form method="POST">
        {% csrf_token %}
        <p>¿Deseas eliminar el producto {{ product.name }}?
        <br>
        <br>
        <button class="btn btn-success" type="submit">Si, eliminar</button>
        <button class="btn btn-danger" type="reset"><a href="{% url 'clients:clients' %}" style="color: white">No, Cancelar</a></button>
        </p>
    </form>
</div>
{% endblock %}

management/templates/products_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Stock
{% endblock %}

{% block headerpage %}
Stock
{% endblock %}

{% block content %}

<div class="container mt-5 text-center">
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header">
                    <h5 style="text-align: center;">Productos totales</h5>
                    <h6 style="text-align: center;">{{ total_products }}</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header">
                    <h5 style="text-align: center;">Producto a punto de agotarse</h5>
                    <h6 style="text-align: center;">{{ total_out_stock2 }}</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header">
                    <h5 style="text-align: center;">Producto sin Stock</h5>
                    <h6 style="text-align: center; color: red;">{{ total_out_stock }}</h6>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="container-fluid mt-5">
    <div class="table-header">
        <div class="search-container">
            <form method="GET" action="{% url 'management:products' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="search" placeholder="Buscar...">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
        </div>
        <div class="add-button">
            <button>
                <a href={%url 'management:add_product' %} style="color:white">Agregar</a>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                </svg>
            </button>
        </div>
    </div>

    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th scope="col" style="text-align: center;">Nombre</th>
                    <th scope="col" style="text-align: center;">Categoria</th>
                    <th scope="col" style="text-align: center;">Precio</th>
                    <th scope="col" style="text-align: center;">Cantidad</th>
                    <th scope="col" style="text-align: center;">Descripcion</th>
                    <th scope="col" style="text-align: center;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td style="text-align: center;">{{ product.name }}</td>
                    {% if product.category == None%}
                        <td style="text-align: center;">Sin Categoria</td>
                    {% else %}
                        <td style="text-align: center;">{{ product.category }}</td>
                    {% endif %}
                    <td style="text-align: center;">{{ product.price }} $</td>
                    <td style="text-align: center;">{{ product.quantity }}</td>
                    <td style="text-align: center;">{{ product.description }}</td>
                    <td style="text-align: center;">
                        <a href="{% url 'management:update_product' product.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'management:delete_product' product.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="9" style="text-align: center;">No se encontro stock disponible.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination-container">
        <button id="prev-page-btn" class="btn btn-secondary btn-sm">Previous</button>
        <button id="next-page-btn" class="btn btn-secondary btn-sm">Next</button>
    </div>
</div>
{% endblock %}