clients/urls.py
from django.urls import path, include
from clients.views import ClientListView, AddClient, UpdateClient, DeleteClient

urlpatterns = [
    path('', ClientListView.as_view(), name='clients'),
    path('add_client/', AddClient.as_view(), name='add_client'),
    path('update_client/<int:pk>/', UpdateClient.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', DeleteClient.as_view(), name='delete_client'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('website.urls', 'website'), namespace='website')),
    path('clients/', include(('clients.urls', 'clients'), namespace='clients')),
    path('jobs/', include(('jobs.urls', 'jobs'), namespace='jobs')),
    path('management/', include(('management.urls', 'management'), namespace='management')),

]

clients/models.py
from django.db import models


#This model is for clients datas
class Client(models.Model):
    name = models.CharField(max_length=100, blank=False, null=True, verbose_name='Name')
    last_name = models.CharField(max_length=100, blank=False, null=True, verbose_name='Last Name')
    full_name = models.CharField(max_length=100, blank=True, null=True, unique=True, verbose_name='Full Name')
    ci = models.CharField(max_length=100, blank=False, null=True, verbose_name='Cedula de Identidad')
    rif = models.CharField(max_length=100, blank=True, null=True, verbose_name='Registro unico de Informacion Fiscal')
    address = models.CharField(max_length=100, blank=False, null=True, verbose_name='Address')
    phone = models.CharField(max_length=100, blank=False, null=True, verbose_name='Phone')
    email = models.EmailField(max_length=100, blank=False, null=True, verbose_name='Email')
    others_datas = models.CharField(max_length=100, blank=True, null=True, verbose_name='Others Datas')


    #This function return name and last name
    def __str__(self):
        return self.name + ' ' + self.last_name
    

    #This class creates the model in the database
    class Meta:
        db_table = 'clients'
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'
        ordering = ['-id']



clients/forms.py
from clients.models import Client
from django import forms



class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

clients/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from clients.models import Client
from clients.forms import ClientForm
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin




class ClientListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Client
    template_name = 'clients_list.html'
    context_object_name = 'clients'
    login_url = 'website:login'
    permission_required = 'clients.view_client'


    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query) |
                Q(last_name__icontains=search_query) |
                Q(ci__icontains=search_query) |
                Q(rif__icontains=search_query) |
                Q(address__icontains=search_query) |
                Q(phone__icontains=search_query) |
                Q(email__icontains=search_query)
            )
        return queryset





#This class creates a client in the database
class AddClient(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'add_client.html'
    success_url = reverse_lazy('clients:clients')
    login_url = 'website:login'
    permission_required = 'clients.add_client'

    def form_valid(self, form):
        form.instance.full_name = form.instance.name + ' ' + form.instance.last_name
        return super().form_valid(form)



#This class update a client in the database
class UpdateClient(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'edit_client.html'
    success_url = reverse_lazy('clients:clients')
    login_url = 'website:login'
    permission_required = 'clients.change_client'

    def form_valid(self, form):
        form.instance.full_name = form.instance.name + ' ' + form.instance.last_name
        return super().form_valid(form)


#This class delete a client in the database
class DeleteClient(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    model = Client
    template_name = 'client_confirm_delete.html'
    success_url = reverse_lazy('clients:clients')
    login_url = 'website:login'
    permission_required = 'clients.delete_client'

clients/templates/add_client.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Agregar Cliente
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 700px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        opacity: 70%;
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }
</style>

<div class="form-container">
    <img class="banner-image" src="{% static 'dist/img/addclient.jpg' %}" alt="Imagen de banner">
    <br>
    <br>
    <h4 style="text-align: center; text-decoration: underline;">Add Client</h4>
    <br>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="name_client">Nombre:</label>
            {{ form.name }}
        </div>
        <div>
            <label for="last_name">Apellidos:</label>
            {{ form.last_name }}
        </div>
        <div>
            <label for="email">Cedula:</label>
            {{ form.ci }}
        </div>
        <div>
            <label for="phone">Rif:</label>
            {{ form.rif }}
        </div>
        <div>
            <label for="address">Telefono:</label>
            {{ form.phone }}
        </div>
        <div>
            <label for="City">Email:</label>
            {{ form.email }}
        </div>
        <div>
            <label for="state">Direccion:</label>
            {{ form.address }}
        </div>
        <div>
            <label for="state">Otros Datos:</label>
            {{ form.others_datas }}
        </div>

        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}

clients/templates/client_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Eliminar Cliente
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 600px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    form button[type="reset"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #f44336;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }


</style>

<div class="form-container">
    <form method="POST">
        {% csrf_token %}
        <p>¿Deseas eliminar el cliente {{ client.name }}?
        <br>
        <br>
        <button class="btn btn-success" type="submit">Si, eliminar</button>
        <button class="btn btn-danger" type="reset"><a href="{% url 'clients:clients' %}" style="color: white">No, Cancelar</a></button>
        </p>
    </form>
</div>
{% endblock %}

clients/templates/clients_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Clientes
{% endblock %}

{% block headerpage %}
Clientes
{% endblock %}

{% block content %}
<div class="container-fluid mt-5">
    <div class="table-header">
        <div class="search-container">
            <form method="GET" action="{% url 'clients:clients' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="search" placeholder="Buscar...">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
        </div>
        <div class="add-button">
            <button>
                <a href={%url 'clients:add_client' %} style="color:white">Agregar</a>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                </svg>
            </button>
        </div>
    </div>

    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th scope="col" style="text-align: center;">Nombre</th>
                    <th scope="col" style="text-align: center;">Apellidos</th>
                    <th scope="col" style="text-align: center;">C.I</th>
                    <th scope="col" style="text-align: center;">RIF</th>
                    <th scope="col" style="text-align: center;">Direccion</th>
                    <th scope="col" style="text-align: center;">Telefono</th>
                    <th scope="col" style="text-align: center;">Email</th>
                    <th scope="col" style="text-align: center;">Otros Datos</th>
                    <th scope="col" style="text-align: center;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for client in clients %}
                <tr>
                    <td style="text-align: center;">{{ client.name }}</td>
                    <td style="text-align: center;">{{ client.last_name }}</td>
                    <td style="text-align: center;">{{ client.ci }}</td>
                    {% if client.rif is None%}
                    <td style="text-align: center;">-</td>
                    {% else %}
                    <td style="text-align: center;">{{ client.rif }}</td>
                    {%endif%}
                    <td style="text-align: center;">{{ client.address }}</td>
                    <td style="text-align: center;">{{ client.phone }}</td>
                    <td style="text-align: center;">{{ client.email }}</td>
                    {% if client.others_datas is None%}
                    <td style="text-align: center;">-</td>
                    {% else%}
                    <td style="text-align: center;">{{ client.others_datas }}</td>
                    {%endif%}
                    <td style="text-align: center;">
                        <a href="{% url 'clients:update_client' client.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'clients:delete_client' client.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="9" style="text-align: center;">No se encontraron clientes.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination-container">
        <button id="prev-page-btn" class="btn btn-secondary btn-sm">Previous</button>
        <button id="next-page-btn" class="btn btn-secondary btn-sm">Next</button>
    </div>
</div>
{% endblock %}

clients/templates/edit_client.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Editar Cliente
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 700px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        opacity: 70%;
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }
</style>

<div class="form-container">
    <img class="banner-image" src="{% static 'dist/img/addclient.jpg' %}" alt="Imagen de banner">
    <br>
    <br>
    <h4 style="text-align: center; text-decoration: underline;">Add Client</h4>
    <br>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="name_client">Nombre:</label>
            {{ form.name }}
        </div>
        <div>
            <label for="last_name">Apellidos:</label>
            {{ form.last_name }}
        </div>
        <div>
            <label for="email">Cedula:</label>
            {{ form.ci }}
        </div>
        <div>
            <label for="phone">Rif:</label>
            {{ form.rif }}
        </div>
        <div>
            <label for="address">Telefono:</label>
            {{ form.phone }}
        </div>
        <div>
            <label for="City">Email:</label>
            {{ form.email }}
        </div>
        <div>
            <label for="state">Direccion:</label>
            {{ form.address }}
        </div>
        <div>
            <label for="state">Otros Datos:</label>
            {{ form.others_datas }}
        </div>

        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}