clients/urls.py
from django.urls import path, include
from clients.views import ClientListView, AddClient, UpdateClient, DeleteClient

urlpatterns = [
    path('', ClientListView.as_view(), name='clients'),
    path('add_client/', AddClient.as_view(), name='add_client'),
    path('update_client/<int:pk>/', UpdateClient.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', DeleteClient.as_view(), name='delete_client'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('website.urls', 'website'), namespace='website')),
    path('clients/', include(('clients.urls', 'clients'), namespace='clients')),
    path('jobs/', include(('jobs.urls', 'jobs'), namespace='jobs')),
    path('management/', include(('management.urls', 'management'), namespace='management')),

]

jobs/urls.py
from django.urls import path, include
from jobs.views import JobListView, AddJob, UpdateJob, DeleteJob


urlpatterns = [
    path('', JobListView.as_view(), name='jobs'),
    path('add_job/', AddJob.as_view(), name='add_job'),
    path('update_job/<int:pk>/', UpdateJob.as_view(), name='update_job'),
    path('delete_job/<int:pk>/', DeleteJob.as_view(), name='delete_job'),
    path('report/', JobListView.generate_excel_report, name='generate_report'),
]


management/urls.py
from django.urls import path, include
from management.views import *

urlpatterns = [
    path('invoices/', InvoiceListView.as_view(), name='invoices'),
    path('invoices/add/', AddInvoice.as_view(), name='add_invoice'),
    path('invoices/update/<int:pk>/', UpdateInvoice.as_view(), name='update_invoice'),
    path('invoices/delete/<int:pk>/', DeleteInvoice.as_view(), name='delete_invoice'),
    path('invoices/view/<int:pk>/', ViewInvoice.as_view(), name='view_invoice'),
    path('invoices/pdf/', InvoiceListView.print_pdf, name='pdf_invoice'),
    path('invoices/report/', InvoiceListView.generate_excel_report, name='generate_report'),
    path('get_product_price/<int:product_id>/', get_product_price, name='get_product_price'),
    path('get_client_data/<int:client_id>/', get_client_datas, name='get_client_datas'),
    path('employees/', EmployeeListView.as_view(), name='employees'),
    path('employees/add/', AddEmployee.as_view(), name='add_employee'),
    path('employees/update/<int:pk>/', UpdateEmployee.as_view(), name='update_employee'),
    path('employees/delete/<int:pk>/', DeleteEmployee.as_view(), name='delete_employee'),
    path('products/', ProductListView.as_view(), name='products'),
    path('products/add/', AddProduct.as_view(), name='add_product'),
    path('products/update/<int:pk>/', UpdateProduct.as_view(), name='update_product'),
    path('products/delete/<int:pk>/', DeleteProduct.as_view(), name='delete_product'),
    path('category/', CategoryListView.as_view(), name='categories'),
    path('category/add/', AddCategory.as_view(), name='add_category'),
    path('category/update/<int:pk>/', UpdateCategory.as_view(), name='update_category'),
    path('category/delete/<int:pk>/', DeleteCategory.as_view(), name='delete_category'),
]

website/urls.py
from django.urls import path, include
from website.views import Index, Login
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='website:login'), name='logout'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | Company</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/customstyles.css' %}">
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'website:index' %}" class="nav-link">Inicio</a>
                </li>
                {% if user.is_authenticated and user.is_superuser %}
                    <li class="nav-item d-none d-sm-inline-block">
                        <a href="{% url 'admin:index' %}" class="nav-link">Admin Panel</a>
                    </li>
                {% endif %}

            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <img src="{% static 'dist/img/logo.png' %}" alt="Top Cauchos Logo" style="height: 50px;">
                
            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="{% url 'website:index' %}" class="brand-link">
                
                <span class="brand-text font-weight-light">Company</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    
                    <div class="info">
                        <a href="#" class="d-block">Bienvenido, {{ user.username }}<a href="{% url 'website:logout' %}" class="nav-link"><i class="bi bi-box-arrow-in-right"> Logout</i></a></a>
                    </div>
                </div>


                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="{% url 'clients:clients' %}" class="nav-link">
                                <i class="bi bi-people"></i>
                                <p href="{% url 'clients:clients' %}">Clientes</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'jobs:jobs' %}" class="nav-link">
                                <i class="bi bi-tools"></i>
                                <p href="{% url 'jobs:jobs' %}">Trabajos</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'management:invoices' %}" class="nav-link">
                                <i class="bi bi-receipt"></i>
                                <p href="{% url 'management:invoices' %}">Facturas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'management:employees' %}" class="nav-link">
                                <i class="bi bi-person-gear"></i>
                                <p href="{% url 'management:employees' %}">Empleados</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'management:products' %}" class="nav-link">
                                <i class="bi bi-cart"></i>
                                <p href="{% url 'management:products' %}">Stock</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'management:categories' %}" class="nav-link">
                                <i class="bi bi-tag"></i>
                                <p href="{% url 'management:categories' %}">Categorias</p>
                            </a>
                        </li>
                    </ul>
                </nav>
                
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div>
                        <div>
                            <h1 class="m-0" style="text-align: center;">{% block headerpage %}{% endblock %}</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            {% block content %}
            {% block bokeh_resources %}
                {{ bokeh_css|safe }}
                {{ bokeh_js|safe }}
            {% endblock %}
            {% block bokeh_script %}{% endblock %}
            {% endblock %}
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->

        <!-- Main Footer -->
        
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- Custom JS -->
    <script src="{% static 'js/customjs.min.js' %}"></script>

</body>

</html>