clients/urls.py
from django.urls import path, include
from clients.views import ClientListView, AddClient, UpdateClient, DeleteClient

urlpatterns = [
    path('', ClientListView.as_view(), name='clients'),
    path('add_client/', AddClient.as_view(), name='add_client'),
    path('update_client/<int:pk>/', UpdateClient.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', DeleteClient.as_view(), name='delete_client'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('website.urls', 'website'), namespace='website')),
    path('clients/', include(('clients.urls', 'clients'), namespace='clients')),
    path('jobs/', include(('jobs.urls', 'jobs'), namespace='jobs')),
    path('management/', include(('management.urls', 'management'), namespace='management')),

]

jobs/urls.py
from django.urls import path, include
from jobs.views import JobListView, AddJob, UpdateJob, DeleteJob


urlpatterns = [
    path('', JobListView.as_view(), name='jobs'),
    path('add_job/', AddJob.as_view(), name='add_job'),
    path('update_job/<int:pk>/', UpdateJob.as_view(), name='update_job'),
    path('delete_job/<int:pk>/', DeleteJob.as_view(), name='delete_job'),
    path('report/', JobListView.generate_excel_report, name='generate_report'),
]


jobs/models.py
from django.db import models
from clients.models import Client
from management.models import Employee

# Create your models here.


class Job(models.Model):
    client = models.ForeignKey(Client, to_field='full_name', blank=False, null=True, on_delete=models.SET_NULL, verbose_name='Client')
    car = models.CharField(max_length=100, blank=False, null=True, verbose_name='Car')
    car_model = models.CharField(max_length=100, blank=False, null=True, verbose_name='Car Model')
    employee = models.ForeignKey(Employee, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Employee')
    description = models.TextField(blank=False, null=True, verbose_name='Description')
    start_date = models.DateField(blank=False, null=True,  verbose_name='Start Date')
    finished = models.BooleanField(default=False, blank=True, verbose_name='Finished')
    end_date = models.DateField(blank=True, null=True, verbose_name='End Date')
    state = models.CharField(max_length=100, blank=True, null=True, verbose_name='State')

    def __str__(self):
        return self.client
    

    class Meta:
        db_table = 'jobs'
        verbose_name = 'Job'
        verbose_name_plural = 'Jobs'
        ordering = ['-id']

jobs/forms.py
from jobs.models import Job
from django import forms




class JobForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'description-field'}))
    class Meta:
        model = Job
        fields = '__all__'
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
            
        }

jobs/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import render
from jobs.models import Job
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.urls import reverse_lazy
from jobs.forms import JobForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from openpyxl import Workbook
from openpyxl.styles import Alignment, PatternFill, Font, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.utils import column_index_from_string




class JobListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Job
    template_name = 'jobs_list.html'
    context_object_name = 'jobs'
    login_url = 'website:login'
    permission_required = 'jobs.view_job'



    def get_queryset(self):
        queryset=super().get_queryset()
        search_query = self.request.GET.get('search')
        year = self.request.GET.get('year')
        if search_query:
            queryset= Job.objects.filter(
                Q(car__icontains=search_query) |
                Q(car_model__icontains=search_query) |
                Q(employee__name__icontains=search_query) |
                Q(state__icontains=search_query)
            )

        if year:
            queryset = queryset.filter(start_date__year=year)

        return queryset
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        jobs_list = Job.objects.all()


        for job in jobs_list:
            if job.finished == False:
                job.state = 'En Curso'
                job.save()
            elif job.finished == True:
                job.state = 'Finalizado'
                job.save()
    

        total_jobs = len(jobs_list)
        finished_jobs = len(jobs_list.filter(finished=True))
        unfinished_jobs = len(jobs_list.filter(finished=False))

        context['total_jobs'] = total_jobs
        context['finished_jobs'] = finished_jobs
        context['unfinished_jobs'] = unfinished_jobs

        years = Job.objects.dates('start_date', 'year', order='DESC')
        years = [year.year for year in years]
        context['years'] = years

        selected_year = self.request.GET.get('year')
        context['selected_year'] = selected_year

        return context
    

    def generate_excel_report(request):


        # The following code is written in Python and is used to filter the issued invoices based on the
        # year provided in the GET request. It retrieves the year value from the GET request using the
        # `request.GET.get('year')` method and then filters the `issuedinvoices` queryset based on the
        # year using the `filter()` method. The `date__year` parameter in the `filter()` method is
        # used to filter the queryset based on the year value.
        year = request.GET.get('year')
        queryset = Job.objects.filter(start_date__year=year).order_by('id')


        # The following code is creating a new Excel workbook and activating the first sheet in the
        # workbook.
        workbook = Workbook()
        sheet = workbook.active


        # The following code is formatting an Excel sheet by merging cells from row 1 to row 3 and columns
        # 1 to 12, adding a title "Report of Issued Invoices" in the merged cell, centering the text,
        # setting the font to bold, size 20, and color white, and filling the cell with a blue color.
        # It also sets the font of cell A1 to bold, size 20, color white, and italic. Finally, it sets
        # the height of row 5 to 30.
        sheet.merge_cells(start_row=1, start_column=1, end_row=3, end_column=7)
        merged_cell = sheet.cell(row=1, column=1)
        merged_cell.value = "Reporte de Trabajos"
        merged_cell.alignment = Alignment(horizontal='center', vertical='center')
        merged_cell.font = Font(bold=True, size=20, color='FFFFFF')
        fill = PatternFill(start_color="00B0F0", end_color="00B0F0", fill_type="solid")
        merged_cell.fill = fill
        sheet['A1'].font = Font(bold=True, size=20, color='FFFFFF', italic=True)
        row_dimension = sheet.row_dimensions[5]
        row_dimension.height = 30


        # The following code is setting the width of all columns in an Excel sheet to 20. The variable
        # `all_columns` contains a list of all the column names, and the `for` loop iterates over each
        # column and sets its width to 20 using the `column_dimensions` attribute of the sheet object.
        all_columns = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'O', 'P']
        for column in all_columns:
            sheet.column_dimensions[column].width = 20


        # The following code is defining a list of headers for a table or spreadsheet. The headers are in
        # multiple languages, as indicated by the use of the `_()` function to translate them. The
        # code then adds three empty rows and the headers to the sheet.
        headers = ['Client', 'Coche', 'Modelo', 'Empleado', 'Descripcion', 'Fecha Inicio', 'Fecha Fin']
        sheet.append([''] * len(headers))
        sheet.append([''] * len(headers))
        sheet.append([''] * len(headers))
        sheet.append(headers)


        # The following code is defining a border style for a header in Python using the `Border` class
        # from the `openpyxl.styles` module. The border style includes thin borders on all sides (top,
        # bottom, left, and right) of the header.
        header_border = Border(
            top=Side(border_style="thin"),
            bottom=Side(border_style="thin"),
            left=Side(border_style="thin"),
            right=Side(border_style="thin")
        )


        # The following code is formatting the header cells of a spreadsheet. It sets the fill color to a
        # light blue shade, makes the font bold and white with a size of 14, centers the text
        # horizontally and vertically, and applies a border to the cells. The code is using the
        # openpyxl library to access and modify the spreadsheet.
        for header_cell in sheet[5]:
            header_cell.fill = PatternFill(start_color="00B0F0", end_color="00B0F0", fill_type="solid")
            header_cell.font = Font(bold=True, color='FFFFFF', size=14)
            header_cell.alignment = Alignment(horizontal='center', vertical='center')
            header_cell.border = header_border


        # The following code is iterating over a queryset of invoices and appending the data of each
        # invoice to a row in a sheet. The row is then added to the sheet and the row index is
        # incremented. The data includes the client name, CIF, invoice number, date, taxable base, IVA
        # rate, IVA, retention, total, due date, paid status, and state of the invoice.
        row_index = 3
        for job in queryset:
            row = [
                f"{job.client.name + ' ' + job.client.last_name}",
                job.car,
                job.car_model,
                f"{job.employee.name + ' ' + job.employee.last_name}" ,
                job.description,
                job.start_date,
                job.end_date,
            ]
            sheet.append(row)
            row_index += 1


        # The following code is defining a border style for a cell in Python using the `Border` class from
        # the `openpyxl.styles` module. The border style includes thin borders on all four sides of
        # the cell (top, bottom, left, and right).
        data_border = Border(
            top=Side(border_style="thin"),
            bottom=Side(border_style="thin"),
            left=Side(border_style="thin"),
            right=Side(border_style="thin")
        )


        # The following code is iterating through all the rows in a sheet (starting from row 6 and ending
        # at row 9000) and then iterating through all the cells in each row. For each cell, it is
        # setting the alignment to be centered both horizontally and vertically, and setting the
        # border to be a specific style (which is defined elsewhere in the code as "data_border").
        for row in sheet.iter_rows(min_row=6, max_row=row_index+2):
            for cell in row:
                cell.alignment = Alignment(horizontal='center', vertical='center')
                cell.border = data_border
        


        # TOTAL JOBS

        jobs = []
        for job in queryset:
            jobs.append(job.client)

        total_jobs = len(jobs)

        sheet.merge_cells(start_row=5, start_column=9, end_row=5, end_column=11)
        merged_cell_total_charged_title = sheet.cell(row=5, column=9)
        merged_cell_total_charged_title.value = "TOTAL TRABAJOS"
        merged_cell_total_charged_title.alignment = Alignment(horizontal='center', vertical='center')
        merged_cell_total_charged_title.font = Font(bold=True, size=15, color='FFFFFF')

        sheet.merge_cells(start_row=6, start_column=9, end_row=6, end_column=11)
        merged_cell_total_charged = sheet.cell(row=6, column=9)
        merged_cell_total_charged.value = f"{total_jobs}"
        merged_cell_total_charged.alignment = Alignment(horizontal='center', vertical='center')
        merged_cell_total_charged.font = Font(bold=True, size=15, color='000000')
        fill = PatternFill(start_color="00B0F0", end_color="00B0F0", fill_type="solid")
        merged_cell_total_charged_title.fill = fill
        merged_cell_total_charged.column = 9

        for row in sheet.iter_rows(min_row=5, max_row=6, min_col=9, max_col=11):
            for cell in row:
                cell.border = data_border


jobs/templates/add_job.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Agregar Trabajo
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 700px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        opacity: 70%;
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    .description-field {
        height: 100px;
    }

</style>

<div class="form-container">
    <img class="banner-image" src="{% static 'dist/img/addjob.jpg' %}" alt="Imagen de banner">
    <br>
    <br>
    <h4 style="text-align: center; text-decoration: underline;">Agregar Trabajo</h4>
    <br>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="name_client">Cliente:</label>
            {{ form.client }}
        </div>
        <div>
            <label for="last_name">Coche:</label>
            {{ form.car }}
        </div>
        <div>
            <label for="email">Modelo:</label>
            {{ form.car_model }}
        </div>
        <div>
            <label for="phone">Empleado:</label>
            {{ form.employee }}
        </div>
        <div>
            <label for="address">Descripción:</label>
            {{ form.description }}
        </div>
        <div>
            <label for="address">Fecha de Inicio:</label>
            {{ form.start_date }}
        </div>
        <div>
            <label for="address">Finalizado:</label>
            {{ form.finished }}
        </div>
        <div>
            <label for="address">Fecha de Fin:</label>
            {{ form.end_date }}
        </div>

        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}

jobs/templates/edit_job.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Agregar Trabajo
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 700px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        opacity: 70%;
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    .description-field {
        height: 100px;
    }

</style>

<div class="form-container">
    <img class="banner-image" src="{% static 'dist/img/addjob.jpg' %}" alt="Imagen de banner">
    <br>
    <br>
    <h4 style="text-align: center; text-decoration: underline;">Agregar Trabajo</h4>
    <br>
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="name_client">Cliente:</label>
            {{ form.client }}
        </div>
        <div>
            <label for="last_name">Coche:</label>
            {{ form.car }}
        </div>
        <div>
            <label for="email">Modelo:</label>
            {{ form.car_model }}
        </div>
        <div>
            <label for="phone">Empleado:</label>
            {{ form.employee }}
        </div>
        <div>
            <label for="address">Descripción:</label>
            {{ form.description }}
        </div>
        <div>
            <label for="address">Fecha de Inicio:</label>
            {{ form.start_date }}
        </div>
        <div>
            <label for="address">Finalizado:</label>
            {{ form.finished }}
        </div>
        <div>
            <label for="address">Fecha de Fin:</label>
            {{ form.end_date }}
        </div>

        <button type="submit">Guardar</button>
    </form>
</div>
{% endblock %}

jobs/templates/job_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Eliminar Trabajo
{% endblock %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .form-container {
        max-width: 600px;
        max-height: 850px;
        margin: 0 auto;
        background-color: white;
        border: 1px solid #ccc;
        border-radius: 5px;
        overflow: hidden;
    }

    .banner-image {
        width: 100%;
        height: 150px;
        object-fit: cover;
        
    }

    form {
        padding: 20px;
        display: grid;
        grid-template-columns: 1fr 1fr;
        grid-gap: 20px;
    }

    form div {
        display: flex;
        flex-direction: column;
        margin-bottom: 20px;
    }

    form label {
        font-weight: bold;
        margin-bottom: 5px;
    }

    form input {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    form button[type="submit"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }

    form button[type="reset"] {
        grid-column: span 2;
        padding: 10px;
        background-color: #f44336;
        color: white;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        font-size: 16px;
    }


</style>

<div class="form-container">
    <form method="POST">
        {% csrf_token %}
        <p>¿Deseas eliminar el trabajo del cliente {{ job.client.full_name }}?
        <br>
        <br>
        <button class="btn btn-success" type="submit">Si, eliminar</button>
        <button class="btn btn-danger" type="reset"><a href="{% url 'clients:clients' %}" style="color: white">No, Cancelar</a></button>
        </p>
    </form>
</div>
{% endblock %}

jobs/templates/jobs_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Trabajos
{% endblock %}

{% block headerpage %}
Trabajos
{% endblock %}

{% block content %}

<div class="container mt-5 text-center">
    <div class="row">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header">
                    <h5 style="text-align: center;">Trabajos Totales</h5>
                    <h6 style="text-align: center;">{{ total_jobs }}</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header">
                    <h5 style="text-align: center;">Trabajos Finalizados</h5>
                    <h6 style="text-align: center;">{{ finished_jobs }}</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header">
                    <h5 style="text-align: center;">Trabajos Pendientes</h5>
                    <h6 style="text-align: center;">{{ unfinished_jobs }}</h6>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid mt-5">
    <div class="table-header">
        <div class="search-container">
            <form method="GET" action="{% url 'jobs:jobs' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="search" placeholder="Buscar...">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </form>
        </div>
        <div class="filter-container">
            <form action="{% url 'jobs:jobs' %}" method="get" class="d-flex align-items-center">
                <label for="year" class="mr-2">Seleccione el año:</label>
                <select name="year" id="year" class="form-control mr-2">
                    {% for year in years %}
                        <option value="{{ year }}" {% if year == selected_year %}selected{% endif %}>{{ year }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="btn btn-primary">Filtrar</button>
            </form>
        </div>
        <div class="filter-container">
            <form method="get" action="{% url 'jobs:generate_report' %}">
                <label for="year">Año:</label>
                <select class="form-select-sm" name="year" id="year">
                    <option value="">Seleccione el año:</option>
                    {% for year in years %}
                    <option value="{{ year }}" {% if year == request.GET.year %}selected{% endif %}>{{ year }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="btn btn-primary">Generar Reporte</button>
            </form>
        </div>
        <div class="add-button">
            <button>
                <a href={%url 'jobs:add_job' %} style="color:white">Agregar</a>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                </svg>
            </button>
        </div>
    </div>

    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th scope="col" style="text-align: center;">Cliente</th>
                    <th scope="col" style="text-align: center;">Coche</th>
                    <th scope="col" style="text-align: center;">Modelo</th>
                    <th scope="col" style="text-align: center;">Empleado</th>
                    <th scope="col" style="text-align: center;">Descripcion</th>
                    <th scope="col" style="text-align: center;">Fecha Inicio</th>
                    <th scope="col" style="text-align: center;">Fecha Fin</th>
                    <th scope="col" style="text-align: center;">Estado</th>
                    <th scope="col" style="text-align: center;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for job in jobs %}
                <tr>
                    <td style="text-align: center;">{{ job.client.full_name }}</td>
                    <td style="text-align: center;">{{ job.car }}</td>
                    <td style="text-align: center;">{{ job.car_model }}</td>
                    <td style="text-align: center;">{{ job.employee.name }}</td>
                    <td style="text-align: center;">{{ job.description }}</td>
                    <td style="text-align: center;">{{ job.start_date }}</td>
                    {% if job.end_date is None %}
                        <td style="text-align: center;">-</td>
                    {% else %}
                        <td style="text-align: center;">{{ job.end_date }}</td>
                    {%endif%}
                    <td style="text-align: center;">{{ job.state }}</td>
                    <td style="text-align: center;">
                        <a href="{% url 'jobs:update_job' job.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'jobs:delete_job' job.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="9" style="text-align: center;">No se encontraron trabajos.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination-container">
        <button id="prev-page-btn" class="btn btn-secondary btn-sm">Previous</button>
        <button id="next-page-btn" class="btn btn-secondary btn-sm">Next</button>
    </div>
</div>
{% endblock %}